#import <Cocoa/Cocoa.h>

/* A test that is part of a Filter.
 */
@interface FilterTestRef : NSObject {
  NSString  *name;

  // Is the test inverted?
  BOOL  inverted;
  
  // Can the inverted state be changed?
  BOOL  canToggleInverted;
}

+ (id) filterTestWithName:(NSString *)name;

/* Creates a filter from a dictionary as generated by -dictionaryForObject.
 */
+ (FilterTestRef *)filterTestRefFromDictionary:(NSDictionary *)dict;

- (id) initWithName:(NSString *)name;
- (id) initWithName:(NSString *)name inverted:(BOOL) inverted;

- (NSString *) name;
- (BOOL) isInverted;

- (void) setCanToggleInverted:(BOOL) flag;
- (BOOL) canToggleInverted;

- (void) toggleInverted;

/* Returns a dictionary that represents the object. It can be used for storing 
 * the object to preferences.
 */
- (NSDictionary *)dictionaryForObject;

@end
